export default {
  LOGIN_TOGGLE:'LOGIN_TOGGLE',
  LOGIN_ADD:'LOGIN_ADD',
  LOGIN_CLEAR:'LOGIN_CLEAR',
  UPDATE_ADDR:'UPDATE_ADDR',
  PRODUCT_LOAD_ALL:'PRODUCT_LOAD_ALL',
  PRODUCT_LOAD_NEW_BOOK:'PRODUCT_LOAD_NEW_BOOK',
  PRODUCT_LOAD_NEW_OTHER:'PRODUCT_LOAD_NEW_OTHER',
  PRODUCT_LOAD_DETAIL:'PRODUCT_LOAD_DETAIL',
  CART_LOAD:'CART_LOAD',
  CART_UPDATE:'CART_UPDATE',
  TOGGLE_STATUS_TAG:'TOGGLE_STATUS_TAG',
  TOGGLE_DIALOG_GOTO_SIGIN:'TOGGLE_DIALOG_GOTO_SIGIN',
  TOGGLE_SHOW_CONFIRM_DELETE:'TOGGLE_SHOW_CONFIRM_DELETE',
  DELETE_ORDER_PRODUCT:'DELETE_ORDER_PRODUCT',
  UPDATE_SHIPPING_TYPE:'UPDATE_SHIPPING_TYPE',
  TOGGLE_SHIELD_PACKAGE:'TOGGLE_SHIELD_PACKAGE'
}