export default {
  LOGIN_TOGGLE:'LOGIN_TOGGLE',
  LOGIN_ADD:'LOGIN_ADD',
  LOGIN_CLEAR:'LOGIN_CLEAR',
  UPDATE_ADDR:'UPDATE_ADDR',
  PRODUCT_LOAD_ALL:'PRODUCT_LOAD_ALL',
  PRODUCT_LOAD_NEW_BOOK:'PRODUCT_LOAD_NEW_BOOK',
  PRODUCT_LOAD_NEW_OTHER:'PRODUCT_LOAD_NEW_OTHER',
  PRODUCT_LOAD_DETAIL:'PRODUCT_LOAD_DETAIL'
}