version: '2'
 
services:
  snufflehp_frontend:
    image: bunyut/yaoi:1.0.0
    container_name: snufflehp_frontend
    command: sh -c "npm i && npm run build && npm run start"
    ports:
      - 80:3000
    volumes:
      - ./snufflehp-app-front:/app
    environment:
      - url_api=http://13.250.34.73:3003
      - API_HOST_URL=http://snufflehp_api
      - NODE_ENV=production

  snufflehp_api:
    image: bunyut/yaoi:1.0.0
    container_name: snufflehp_api
    command: sh -c "npm i && npm run prod"
    ports:
      - 3003:3005
    volumes:
      - ./snufflehp-app-api:/app
    environment:
      - db=snuffle-db.cdxjjnzzkref.ap-southeast-1.rds.amazonaws.com
      - DB_HOST=snuffle-db.cdxjjnzzkref.ap-southeast-1.rds.amazonaws.com
      - DB_USER=snuffle
      - DB_PASS=jjtomson
    
  # mysql_snufflehp:
  #   image: mysql:5.6
  #   container_name: mysql_snufflehp
  #   ports:
  #     - 3305:3306
  #   volumes:
  #     - .:/drive_a
  #     - ./sufflehp-db:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=123456

# networks:
#   default:
#     external:
#       name: snufflehp_network