version: '2'

services:
  snufflehp_frontend:
    image: bunyut/yaoi:1.0.0
    container_name: snufflehp_frontend
    command: sh -c "npm run start"
    ports:
      - 80:3000
    volumes:
      - ./snufflehp-app-front:/app
    environment:
      - url_api=http://52.220.171.107:3003
      - API_HOST_URL=http://52.220.171.107:3003
      - NODE_ENV=production

  snufflehp_api:
    image: bunyut/yaoi:1.0.0
    container_name: snufflehp_api
    command: sh -c "npm i && npm run prod"
    ports:
      - 3003:3005
    volumes:
      - ./snufflehp-app-api:/app
    environment:
       - db=mysql_snufflehp
       - DB_HOST=mysql_snufflehp
       - DB_USER=root
       - DB_PASS=123456

networks:
  default:
    external:
      name: snufflehp_network