version: '2'
 
services:
  snufflehp_frontend:
    image: bunyut/yaoi:1.0.0
    container_name: snufflehp_frontend
    command: npm run dev
    ports:
      - 80:3000
    volumes:
      - ./snufflehp-app-front:/app
    environment:
      - url_api=http://ec2-54-255-245-192.ap-southeast-1.compute.amazonaws.com:3003
      - API_HOST_URL=http://ec2-54-255-245-192.ap-southeast-1.compute.amazonaws.com:3003

  snufflehp_api:
    image: bunyut/yaoi:1.0.0
    container_name: snuffle_api
    command: npm run dev
    ports:
      - 3003:3005
    volumes:
      - ./snufflehp-app-api:/app
    environment:
      - db=snuffle-db.cdxjjnzzkref.ap-southeast-1.rds.amazonaws.com
      - DB_HOST=snuffle-db.cdxjjnzzkref.ap-southeast-1.rds.amazonaws.com
      - DB_USER=root
      - DB_PASS=123456